import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/nav";
import { ThemeProvider } from "@/context/darkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Learn Tailwind CSS",
  description: "Generated by ME",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <body className={clsx(inter.className, "bg-slate-200 dark:bg-black")}>
            <Nav />
            {children}
          </body>
        </ThemeProvider>
      </body>
    </html>
  );
}
